language: rust
dist: trusty
sudo: false
cache:
  directories:
    - "$HOME/texlive/2016/texmf-var/luatex-cache"
    - "$HOME/.cargo"
    - "$HOME/rust"
addons:
  apt:
    packages:
      - pandoc
before_install:
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/install-tex.sh
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/tlmgr.sh
  - chmod +x install-tex.sh tlmgr.sh
  - curl -L -O http://downloads.sourceforge.net/project/dejavu/dejavu/2.35/dejavu-fonts-ttf-2.35.zip
  - unzip dejavu-fonts-ttf-2.35.zip
  - mkdir "$HOME/.fonts"
  - cp dejavu-fonts-ttf-2.35/ttf/*.ttf "$HOME/.fonts/"
  - fc-cache -f -v
install:
  - . ./install-tex.sh
  - ./tlmgr.sh update --self --all || echo "ignore errors"
  - ./tlmgr.sh install collection-luatex collection-langjapanese collection-fontsrecommended type1cm mdframed needspace hyphenat quotchap framed everyhook svn-prov
before_script:
  - cp trpl_meta.yml trpl-ebook/
  - "echo \"pub const RELEASE_DATE: &'static str = \\\"`date +%F`\\\";\" | cat - options.rs.template > options.rs"
  - cp options.rs trpl-ebook/src/convert_book/
  - rm -rf trpl-ebook/trpl
  - cp -r the-rust-programming-language-ja/1.9/ja/book trpl-ebook/trpl
script:
  - cd trpl-ebook
  - cargo run --release
  - cp dist/*a4.pdf ../a4.pdf
  - cp dist/*letter.pdf ../letter.pdf
  - cd ..
after_success:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
  - openssl aes-256-cbc -k "$SERVER_KEY" -in deploy_key.enc -d -a -out deploy.key
  - cp deploy.key ~/.ssh/
  - chmod 600 ~/.ssh/deploy.key
  - git config --global user.email "m@yyu.pw"
  - git config --global user.name "Yoshimura Yuu"
  - git fetch origin gh-pages:gh-pages
  - git stash -u
  - git checkout gh-pages
  - rm a4.pdf letter.pdf
  - git stash pop
  - git add a4.pdf letter.pdf
  - git commit -a -m "auto commit on travis $TRAVIS_JOB_NUMBER $TRAVIS_COMMIT"
  - git push git@github.com:rust-lang-ja/trpl-ja-pdf.git gh-pages:gh-pages
env:
  global:
    secure: ck1uVFgjw0jFayZgV9enDV3n4/D5PiyW3J/ahpHHhTaO9H4tGl6vKzlsbbo9zCPRmYpHyjH/mnEDcfWXViRE72o4wYxA4zbK+JNzJK5mFUuSZB4WrD44HC9jIL99u3mLU+9DnlK6gbE3oz6JRI04Ie9L48+LeCAX6HS4iAuj8ddRIgkVUEKoZPhJ7AbFNcBtU91uQqRmpLWXeLKgkwC9jSmD//zC0DkdTHGoCD2aUCARiwBbWLn17oV8nI37eUEgV/ZaPDmwoV1JSR9KFiokWTH4QiRwwKXnw5n2nHJPmBCmEs5LmQlsuu8puZmlXg6m8xUTIheW0vTbxejZeoNP71M+7MXGP0Ix6Z1rDrx767GORjUpwhSgVwmrz7VCSgZYwze9v2j0NWsDaDXD4kruxF4j7c7YdhzPA/+K6I+NdwVE3zGyRzG6KUySbVXGAFIMzIt/yofTN1PeSy779nrnMiNI9N8AyikYmiT1ocT91j7HzMYTab250yugm6Tl80+wwlpbk0ljYR7m0ZBIopAS8HzzeSrD9Qww6PAQ9EBPvnIlhG62ttUAjRFHe7zrDSzWaD2WvdM+jmeEGCdc1iqQLteWgvsLbXOJd5GJksOgRX/rRa++ioq2/+P/aGEyFeNXWMD3ru2V3eDDL2kBpnLv93JmsdRorGsFDOFsau2i0TI=
